In [37]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv("./Desktop/Data1.csv")

In [39]:
df.head()

,Metric,Operating System Type,30-05-2024,31-05-2024,01-06-2024,02-06-2024,03-06-2024,04-06-2024,05-06-2024,06-06-2024,...,18-08-2024,19-08-2024,20-08-2024,21-08-2024,22-08-2024,23-08-2024,24-08-2024,25-08-2024,26-08-2024,27-08-2024
0,Devices Page Visits,Apple iOS,3370,3383,3085,2836,3353,3402,3229,3388,...,3339,3573,3321,4459,3690,3914,3351,2984,3420,3403
1,Devices Page Visits,Google Android,1751,1804,1571,1512,1602,1804,1659,1748,...,1720,1802,1717,2128,1793,1961,1627,1558,1597,1576
2,Started Troubleshooting (Solution Center),Apple iOS,2052,1936,1851,1774,1946,2052,1893,2052,...,2176,2187,2074,2838,2336,2519,2150,2027,2094,2096
3,Started Troubleshooting (Solution Center),Google Android,976,967,909,874,852,1012,918,990,...,1026,1004,1023,1226,1010,1114,949,960,887,924
4,Saw a Result,Apple iOS,291,257,247,290,322,324,261,222,...,148,136,105,107,85,71,65,74,67,68

In [40]:
df.columns

Index(['Metric', 'Operating System Type', '30-05-2024', '31-05-2024',
       '01-06-2024', '02-06-2024', '03-06-2024', '04-06-2024', '05-06-2024',
       '06-06-2024', '07-06-2024', '08-06-2024', '09-06-2024', '10-06-2024',
       '11-06-2024', '12-06-2024', '13-06-2024', '14-06-2024', '15-06-2024',
       '16-06-2024', '17-06-2024', '18-06-2024', '19-06-2024', '20-06-2024',
       '21-06-2024', '22-06-2024', '23-06-2024', '24-06-2024', '25-06-2024',
       '26-06-2024', '27-06-2024', '28-06-2024', '29-06-2024', '30-06-2024',
       '01-07-2024', '02-07-2024', '03-07-2024', '04-07-2024', '05-07-2024',
       '06-07-2024', '07-07-2024', '08-07-2024', '09-07-2024', '10-07-2024',
       '11-07-2024', '12-07-2024', '13-07-2024', '14-07-2024', '15-07-2024',
       '16-07-2024', '17-07-2024', '18-07-2024', '19-07-2024', '20-07-2024',
       '21-07-2024', '22-07-2024', '23-07-2024', '24-07-2024', '25-07-2024',
       '26-07-2024', '27-07-2024', '28-07-2024', '29-07-2024', '30-07-2024',
       '31-07-2024', '01-08-2024', '02-08-2024', '03-08-2024', '04-08-2024',
       '05-08-2024', '06-08-2024', '07-08-2024', '08-08-2024', '09-08-2024',
       '10-08-2024', '11-08-2024', '12-08-2024', '13-08-2024', '14-08-2024',
       '15-08-2024', '16-08-2024', '17-08-2024', '18-08-2024', '19-08-2024',
       '20-08-2024', '21-08-2024', '22-08-2024', '23-08-2024', '24-08-2024',
       '25-08-2024', '26-08-2024', '27-08-2024'],
      dtype='object')

In [41]:
# Step 2: Identify the columns for melting
date_columns = df.columns[2:].tolist()
id_vars = ['Metric', 'Operating System Type']

In [42]:
# Step 3: Melt the DataFrame to long format
df_melted = df.melt(id_vars=id_vars, value_vars=date_columns, var_name='Date', value_name='Value')

# Step 4: Pivot the table to the desired format
df_pivot = df_melted.pivot_table(index=['Date', 'Operating System Type'], columns='Metric', values='Value', aggfunc='first').reset_index()

# Step 5: Clean up the DataFrame
df_pivot.columns.name = None  # Remove the columns' name

# Assign pivoted DataFrame back to df
df = df_pivot

In [43]:
df.head()

,Date,Operating System Type,1st common reason (Unknown),2nd common reason (Disconnected),3rd common reason (Incomplete Install),Clicked Billing & Account Support,Clicked Homelife Support,Clicked Internet Support,Clicked TV Support,Connect with Agent,Devices Page Visits,Did a Device Reboot,Interacted with Chat,Interacted with Chat_1,Reset Complete,Saw a Result,Schedule Tech,Started P&P troubleshooting,Started Proactive and Preventive (P&P),Started Troubleshooting (Solution Center)
0,01-06-2024,Apple iOS,146,17,37,606,7,578,23,82,3085,64,240,139,231,247,408,950,1607,1851
1,01-06-2024,Google Android,60,10,10,273,8,255,22,19,1571,34,129,43,95,95,126,422,810,909
2,01-07-2024,Apple iOS,161,7,29,778,10,678,42,80,3547,63,250,162,250,299,435,976,1775,2076
3,01-07-2024,Google Android,53,7,4,342,8,248,15,28,1737,30,108,53,92,100,132,450,844,949
4,01-08-2024,Apple iOS,112,8,29,692,4,673,28,72,3457,63,292,128,300,209,418,1014,1864,2059

In [44]:
# Creating new columns as per the specified calculations and rounding off to 1 decimal places
df['1st common reason (Unknown) %'] = (df['1st common reason (Unknown)'] / df['Saw a Result'] * 100).round(3)
df['2nd common reason (Disconnected) %'] = (df['2nd common reason (Disconnected)'] / df['Saw a Result'] * 100).round(3)
df['3rd common reason (Incomplete Install) %'] = (df['3rd common reason (Incomplete Install)'] / df['Saw a Result'] * 100).round(3)
df['Clicked Billing & Account Support %'] = (df['Clicked Billing & Account Support'] / df['Devices Page Visits'] * 100).round(3)
df['Clicked Homelife Support %'] = (df['Clicked Homelife Support'] / df['Devices Page Visits'] * 100).round(3)
df['Clicked Internet Support %'] = (df['Clicked Internet Support'] / df['Devices Page Visits'] * 100).round(3)
df['Clicked TV Support %'] = (df['Clicked TV Support'] / df['Devices Page Visits'] * 100).round(3)
df['Connect with Agent %'] = (df['Connect with Agent'] / df['Started Proactive and Preventive (P&P)'] * 100).round(3)
df['Did a Device Reboot %'] = (df['Did a Device Reboot'] / df['Devices Page Visits'] * 100).round(3)
df['Interacted with Chat %'] = (df['Interacted with Chat'] / df['Started Proactive and Preventive (P&P)'] * 100).round(3)
df['Interacted with Chat_1 %'] = (df['Interacted with Chat_1'] / df['Devices Page Visits'] * 100).round(3)
df['Reset Complete %'] = (df['Reset Complete'] / df['Started Proactive and Preventive (P&P)'] * 100).round(3)
df['Saw a Result %'] = (df['Saw a Result'] / df['Started Troubleshooting (Solution Center)'] * 100).round(3)
df['Schedule Tech %'] = (df['Schedule Tech'] / df['Started Proactive and Preventive (P&P)'] * 100).round(3)
df['Started P&P troubleshooting %'] = (df['Started P&P troubleshooting'] / df['Started Proactive and Preventive (P&P)'] * 100).round(3)
df['Started Proactive and Preventive (P&P) %'] = (df['Started Proactive and Preventive (P&P)'] / df['Devices Page Visits'] * 100).round(3)
df['Started Troubleshooting (Solution Center) %'] = (df['Started Troubleshooting (Solution Center)'] / df['Devices Page Visits'] * 100).round(3)

df.head()

,Date,Operating System Type,1st common reason (Unknown),2nd common reason (Disconnected),3rd common reason (Incomplete Install),Clicked Billing & Account Support,Clicked Homelife Support,Clicked Internet Support,Clicked TV Support,Connect with Agent,...,Connect with Agent %,Did a Device Reboot %,Interacted with Chat %,Interacted with Chat_1 %,Reset Complete %,Saw a Result %,Schedule Tech %,Started P&P troubleshooting %,Started Proactive and Preventive (P&P) %,Started Troubleshooting (Solution Center) %
0,01-06-2024,Apple iOS,146,17,37,606,7,578,23,82,...,5.103,2.075,14.935,4.506,14.375,13.344,25.389,59.116,52.091,60.000
1,01-06-2024,Google Android,60,10,10,273,8,255,22,19,...,2.346,2.164,15.926,2.737,11.728,10.451,15.556,52.099,51.560,57.861
2,01-07-2024,Apple iOS,161,7,29,778,10,678,42,80,...,4.507,1.776,14.085,4.567,14.085,14.403,24.507,54.986,50.042,58.528
3,01-07-2024,Google Android,53,7,4,342,8,248,15,28,...,3.318,1.727,12.796,3.051,10.900,10.537,15.640,53.318,48.590,54.634
4,01-08-2024,Apple iOS,112,8,29,692,4,673,28,72,...,3.863,1.822,15.665,3.703,16.094,10.151,22.425,54.399,53.920,59.560

In [45]:
# Melt the DataFrame to have a long format
melted_df = df.melt(id_vars=['Date', 'Operating System Type'], var_name='Metric', value_name='Value')

# Pivot the DataFrame
pivoted_df = melted_df.pivot_table(
    index=['Operating System Type', 'Metric'],
    columns='Date',
    values='Value',
    aggfunc='first'
).reset_index()

# Rename the columns to reflect the date values directly
pivoted_df.columns.name = None  # Remove the index name
pivoted_df.columns = ['Operating System Type', 'Metric'] + list(pivoted_df.columns[2:])  # Keep date values as column names
pivoted_df.head()

,Operating System Type,Metric,01-06-2024,01-07-2024,01-08-2024,02-06-2024,02-07-2024,02-08-2024,03-06-2024,03-07-2024,...,27-08-2024,28-06-2024,28-07-2024,29-06-2024,29-07-2024,30-05-2024,30-06-2024,30-07-2024,31-05-2024,31-07-2024
0,Apple iOS,1st common reason (Unknown),146.000,161.000,112.000,158.000,152.000,115.000,167.000,131.000,...,54.000,126.000,89.000,151.000,100.000,172.000,149.000,115.000,181.000,130.000
1,Apple iOS,1st common reason (Unknown) %,59.109,53.846,53.589,54.483,58.015,55.556,51.863,50.385,...,79.412,48.092,57.051,61.134,57.803,59.107,66.518,59.278,70.428,59.361
2,Apple iOS,2nd common reason (Disconnected),17.000,7.000,8.000,13.000,10.000,10.000,8.000,11.000,...,9.000,11.000,7.000,10.000,7.000,12.000,13.000,10.000,14.000,14.000
3,Apple iOS,2nd common reason (Disconnected) %,6.883,2.341,3.828,4.483,3.817,4.831,2.484,4.231,...,13.235,4.198,4.487,4.049,4.046,4.124,5.804,5.155,5.447,6.393
4,Apple iOS,3rd common reason (Incomplete Install),37.000,29.000,29.000,23.000,39.000,23.000,28.000,29.000,...,3.000,31.000,23.000,41.000,23.000,22.000,19.000,26.000,25.000,21.000

In [46]:
pivoted_df.shape

(70, 92)

In [47]:
# Function to calculate the sum for a given metric and operating system
def calculate_sum(df, os_type, metric):
    return df[(df['Operating System Type'] == os_type) & (df['Metric'] == metric)].iloc[:, 2:].sum()

# Calculate sums for both operating systems for "Devices Page Visits"
date_columns = pivoted_df.columns[2:]
both_row = {'Operating System Type': 'Both', 'Metric': 'Devices Page Visits'}

both_row.update({date: calculate_sum(pivoted_df, 'Google Android', 'Devices Page Visits')[date] +
                 calculate_sum(pivoted_df, 'Apple iOS', 'Devices Page Visits')[date] for date in date_columns})

# Create and concatenate new row DataFrame
combined_df = pd.concat([pivoted_df, pd.DataFrame([both_row])], ignore_index=True)

# Function to calculate metrics for "Both"
def calculate_metric_both(df, metric_name):
    both_row = {'Operating System Type': 'Both', 'Metric': metric_name}
    for date in date_columns:
        android_numerator = (calculate_sum(df, 'Google Android', metric_name)[date] *
                             calculate_sum(df, 'Google Android', 'Devices Page Visits')[date])
        
        apple_numerator = (calculate_sum(df, 'Apple iOS', metric_name)[date] *
                           calculate_sum(df, 'Apple iOS', 'Devices Page Visits')[date])
        
        numerator = android_numerator + apple_numerator
        devices_visits_both = df.loc[
            (df['Operating System Type'] == 'Both') & 
            (df['Metric'] == 'Devices Page Visits'), date
        ].values[0]
        
        both_row[date] = numerator / devices_visits_both if devices_visits_both > 0 else 0

    return pd.DataFrame([both_row])

# Calculate new metrics for various percentages
combined_df = pd.concat([combined_df, calculate_metric_both(combined_df, "Started Troubleshooting (Solution Center) %")], ignore_index=True)
combined_df = pd.concat([combined_df, calculate_metric_both(combined_df, "Interacted with Chat_1 %")], ignore_index=True)
combined_df = pd.concat([combined_df, calculate_metric_both(combined_df, "Clicked Homelife Support %")], ignore_index=True)
combined_df = pd.concat([combined_df, calculate_metric_both(combined_df, "Clicked TV Support %")], ignore_index=True)
combined_df = pd.concat([combined_df, calculate_metric_both(combined_df, "Did a Device Reboot %")], ignore_index=True)
combined_df = pd.concat([combined_df, calculate_metric_both(combined_df, "Started Proactive and Preventive (P&P) %")], ignore_index=True)
combined_df = pd.concat([combined_df, calculate_metric_both(combined_df, "Clicked Internet Support %")], ignore_index=True)
combined_df = pd.concat([combined_df, calculate_metric_both(combined_df, "Clicked Billing & Account Support %")], ignore_index=True)

combined_df[['Operating System Type', 'Metric', '27-08-2024']]

   Operating System Type                                    Metric  27-08-2024
0              Apple iOS               1st common reason (Unknown)   54.000000
1              Apple iOS             1st common reason (Unknown) %   79.412000
2              Apple iOS          2nd common reason (Disconnected)    9.000000
3              Apple iOS        2nd common reason (Disconnected) %   13.235000
4              Apple iOS    3rd common reason (Incomplete Install)    3.000000
..                   ...                                       ...         ...
74                  Both                      Clicked TV Support %    1.024015
75                  Both                     Did a Device Reboot %    0.903599
76                  Both  Started Proactive and Preventive (P&P) %   59.087814
77                  Both                Clicked Internet Support %   16.890503
78                  Both       Clicked Billing & Account Support %   19.281013

[79 rows x 3 columns]

In [48]:
# Select only the relevant date columns
date_columns = combined_df.columns[2:]

# Initialize a list to hold the rows for all metrics
both_rows = []

# Calculate the new metric for "Both" for "Saw a Result"
saw_result_row = {
    'Operating System Type': 'Both',
    'Metric': "Saw a Result %"
}

for date in date_columns:
    # Calculate the numerator
    android_numerator = combined_df[
        (combined_df['Operating System Type'] == 'Google Android') & 
        (combined_df['Metric'] == 'Saw a Result')
    ][date].sum()  # Use .sum() to handle multiple rows
    
    apple_numerator = combined_df[
        (combined_df['Operating System Type'] == 'Apple iOS') & 
        (combined_df['Metric'] == 'Saw a Result')
    ][date].sum()  # Use .sum() to handle multiple rows
    
    numerator = android_numerator + apple_numerator
    
    # Calculate the denominator
    started_troubleshooting_both = combined_df.loc[
        (combined_df['Operating System Type'] == 'Google Android') & 
        (combined_df['Metric'] == 'Started Troubleshooting (Solution Center)'),
        date
    ].sum() + combined_df.loc[
        (combined_df['Operating System Type'] == 'Apple iOS') & 
        (combined_df['Metric'] == 'Started Troubleshooting (Solution Center)'),
        date
    ].sum()
    
    # Calculate the final value for "Saw a Result" in percentage
    saw_result_row[date] = (numerator / started_troubleshooting_both * 100) if started_troubleshooting_both > 0 else 0

# Append the "Saw a Result" row
both_rows.append(saw_result_row)

# Calculate the new metric for "1st common reason (Unknown)"
unknown_reason_row = {
    'Operating System Type': 'Both',
    'Metric': "1st common reason (Unknown) %"
}

for date in date_columns:
    # Calculate the numerator
    android_numerator = combined_df[
        (combined_df['Operating System Type'] == 'Google Android') & 
        (combined_df['Metric'] == '1st common reason (Unknown)')
    ][date].sum()  # Use .sum() to handle multiple rows
    
    apple_numerator = combined_df[
        (combined_df['Operating System Type'] == 'Apple iOS') & 
        (combined_df['Metric'] == '1st common reason (Unknown)')
    ][date].sum()  # Use .sum() to handle multiple rows
    
    numerator = android_numerator + apple_numerator
    
    # Calculate the denominator
    saw_result_both = combined_df.loc[
        (combined_df['Operating System Type'] == 'Google Android') & 
        (combined_df['Metric'] == 'Saw a Result'),
        date
    ].sum() + combined_df.loc[
        (combined_df['Operating System Type'] == 'Apple iOS') & 
        (combined_df['Metric'] == 'Saw a Result'),
        date
    ].sum()
    
    # Calculate the final value for "1st common reason (Unknown)" in percentage
    unknown_reason_row[date] = (numerator / saw_result_both * 100) if saw_result_both > 0 else 0

# Append the "1st common reason (Unknown)" row
both_rows.append(unknown_reason_row)

# Calculate the new metric for "2nd common reason (Disconnected)"
disconnected_row = {
    'Operating System Type': 'Both',
    'Metric': "2nd common reason (Disconnected) %"
}

for date in date_columns:
    # Calculate the numerator
    android_numerator = combined_df[
        (combined_df['Operating System Type'] == 'Google Android') & 
        (combined_df['Metric'] == '2nd common reason (Disconnected)')
    ][date].sum()  # Use .sum() to handle multiple rows
    
    apple_numerator = combined_df[
        (combined_df['Operating System Type'] == 'Apple iOS') & 
        (combined_df['Metric'] == '2nd common reason (Disconnected)')
    ][date].sum()  # Use .sum() to handle multiple rows
    
    numerator = android_numerator + apple_numerator
    
    # Calculate the denominator
    disconnected_both = combined_df.loc[
        (combined_df['Operating System Type'] == 'Google Android') & 
        (combined_df['Metric'] == 'Saw a Result'),
        date
    ].sum() + combined_df.loc[
        (combined_df['Operating System Type'] == 'Apple iOS') & 
        (combined_df['Metric'] == 'Saw a Result'),
        date
    ].sum()
    
    # Calculate the final value for "2nd common reason (Disconnected)" in percentage
    disconnected_row[date] = (numerator / disconnected_both * 100) if disconnected_both > 0 else 0

# Append the "2nd common reason (Disconnected)" row
both_rows.append(disconnected_row)

# Calculate the new metric for "3rd common reason (Incomplete Install)"
incomplete_install_row = {
    'Operating System Type': 'Both',
    'Metric': "3rd common reason (Incomplete Install) %"
}

for date in date_columns:
    # Calculate the numerator
    android_numerator = combined_df[
        (combined_df['Operating System Type'] == 'Google Android') & 
        (combined_df['Metric'] == '3rd common reason (Incomplete Install)')
    ][date].sum()  # Use .sum() to handle multiple rows
    
    apple_numerator = combined_df[
        (combined_df['Operating System Type'] == 'Apple iOS') & 
        (combined_df['Metric'] == '3rd common reason (Incomplete Install)')
    ][date].sum()  # Use .sum() to handle multiple rows
    
    numerator = android_numerator + apple_numerator
    
    # Calculate the denominator
    incomplete_install_both = combined_df.loc[
        (combined_df['Operating System Type'] == 'Google Android') & 
        (combined_df['Metric'] == 'Saw a Result'),
        date
    ].sum() + combined_df.loc[
        (combined_df['Operating System Type'] == 'Apple iOS') & 
        (combined_df['Metric'] == 'Saw a Result'),
        date
    ].sum()
    
    # Calculate the final value for "3rd common reason (Incomplete Install)" in percentage
    incomplete_install_row[date] = (numerator / incomplete_install_both * 100) if incomplete_install_both > 0 else 0

# Append the "3rd common reason (Incomplete Install)" row
both_rows.append(incomplete_install_row)

# Create a DataFrame for the new rows
both_df = pd.DataFrame(both_rows)

# Concatenate the new rows to the original combined DataFrame
combined_df = pd.concat([combined_df, both_df], ignore_index=True)

combined_df[['Operating System Type', 'Metric', '27-08-2024']]

   Operating System Type                                    Metric  27-08-2024
0              Apple iOS               1st common reason (Unknown)   54.000000
1              Apple iOS             1st common reason (Unknown) %   79.412000
2              Apple iOS          2nd common reason (Disconnected)    9.000000
3              Apple iOS        2nd common reason (Disconnected) %   13.235000
4              Apple iOS    3rd common reason (Incomplete Install)    3.000000
..                   ...                                       ...         ...
78                  Both       Clicked Billing & Account Support %   19.281013
79                  Both                            Saw a Result %    2.947020
80                  Both             1st common reason (Unknown) %   82.022472
81                  Both        2nd common reason (Disconnected) %   11.235955
82                  Both  3rd common reason (Incomplete Install) %    4.494382

[83 rows x 3 columns]

In [49]:
#TO BE UESD

# Select only the relevant date columns
date_columns = combined_df.columns[2:]

# Initialize a list to hold the rows for all metrics
results_rows = []

# Define a function to calculate metrics
def calculate_metric(metric_name, numerator_conditions, denominator_conditions):
    metric_row = {
        'Operating System Type': 'Both',
        'Metric': metric_name
    }
    
    for date in date_columns:
        # Calculate the numerator
        android_numerator = combined_df[
            (combined_df['Operating System Type'] == 'Google Android') & 
            (combined_df['Metric'].isin(numerator_conditions))
        ][date].sum()

        apple_numerator = combined_df[
            (combined_df['Operating System Type'] == 'Apple iOS') & 
            (combined_df['Metric'].isin(numerator_conditions))
        ][date].sum()

        numerator = android_numerator + apple_numerator
        
        # Calculate the denominator
        android_denominator = combined_df[
            (combined_df['Operating System Type'] == 'Google Android') & 
            (combined_df['Metric'].isin(denominator_conditions))
        ][date].sum()

        apple_denominator = combined_df[
            (combined_df['Operating System Type'] == 'Apple iOS') & 
            (combined_df['Metric'].isin(denominator_conditions))
        ][date].sum()

        denominator = android_denominator + apple_denominator

        # Calculate the final value in percentage
        metric_row[date] = (numerator / denominator * 100) if denominator > 0 else 0
    
    return metric_row

# Calculate each metric
results_rows.append(calculate_metric(
    "Started P&P troubleshooting %",
    ["Started P&P troubleshooting"],
    ["Started Proactive and Preventive (P&P)"]
))

results_rows.append(calculate_metric(
    "Reset Complete %",
    ["Reset Complete"],
    ["Started Proactive and Preventive (P&P)"]
))

results_rows.append(calculate_metric(
    "Schedule Tech %",
    ["Schedule Tech"],
    ["Started Proactive and Preventive (P&P)"]
))

results_rows.append(calculate_metric(
    "Connect with Agent %",
    ["Connect with Agent"],
    ["Started Proactive and Preventive (P&P)"]
))

results_rows.append(calculate_metric(
    "Interacted with Chat %",
    ["Interacted with Chat"],
    ["Started Proactive and Preventive (P&P)"]
))

# Create a DataFrame for the new rows
results_df = pd.DataFrame(results_rows)

# Concatenate the new rows to the original combined DataFrame
combined_df1 = pd.concat([combined_df, results_df], ignore_index=True)
combined_df1[['Operating System Type', 'Metric', '27-08-2024']]

   Operating System Type                                  Metric  27-08-2024
0              Apple iOS             1st common reason (Unknown)   54.000000
1              Apple iOS           1st common reason (Unknown) %   79.412000
2              Apple iOS        2nd common reason (Disconnected)    9.000000
3              Apple iOS      2nd common reason (Disconnected) %   13.235000
4              Apple iOS  3rd common reason (Incomplete Install)    3.000000
..                   ...                                     ...         ...
83                  Both           Started P&P troubleshooting %   54.724677
84                  Both                        Reset Complete %   16.961251
85                  Both                         Schedule Tech %   20.360299
86                  Both                    Connect with Agent %    4.146839
87                  Both                  Interacted with Chat %   14.445955

[88 rows x 3 columns]

In [50]:
#Till the above point we have all KPIs calculated for Android, Both, Google

In [51]:
combined_df1.shape

(88, 92)

In [52]:
combined_df1.head()

,Operating System Type,Metric,01-06-2024,01-07-2024,01-08-2024,02-06-2024,02-07-2024,02-08-2024,03-06-2024,03-07-2024,...,27-08-2024,28-06-2024,28-07-2024,29-06-2024,29-07-2024,30-05-2024,30-06-2024,30-07-2024,31-05-2024,31-07-2024
0,Apple iOS,1st common reason (Unknown),146.000,161.000,112.000,158.000,152.000,115.000,167.000,131.000,...,54.000,126.000,89.000,151.000,100.000,172.000,149.000,115.000,181.000,130.000
1,Apple iOS,1st common reason (Unknown) %,59.109,53.846,53.589,54.483,58.015,55.556,51.863,50.385,...,79.412,48.092,57.051,61.134,57.803,59.107,66.518,59.278,70.428,59.361
2,Apple iOS,2nd common reason (Disconnected),17.000,7.000,8.000,13.000,10.000,10.000,8.000,11.000,...,9.000,11.000,7.000,10.000,7.000,12.000,13.000,10.000,14.000,14.000
3,Apple iOS,2nd common reason (Disconnected) %,6.883,2.341,3.828,4.483,3.817,4.831,2.484,4.231,...,13.235,4.198,4.487,4.049,4.046,4.124,5.804,5.155,5.447,6.393
4,Apple iOS,3rd common reason (Incomplete Install),37.000,29.000,29.000,23.000,39.000,23.000,28.000,29.000,...,3.000,31.000,23.000,41.000,23.000,22.000,19.000,26.000,25.000,21.000

In [53]:
melted_df = pd.melt(combined_df1, id_vars=['Metric', 'Operating System Type'], 
                     value_vars=combined_df1.columns[2:], 
                     var_name='Date', 
                     value_name='Value')
melted_df.head()

,Metric,Operating System Type,Date,Value
0,1st common reason (Unknown),Apple iOS,01-06-2024,146.000
1,1st common reason (Unknown) %,Apple iOS,01-06-2024,59.109
2,2nd common reason (Disconnected),Apple iOS,01-06-2024,17.000
3,2nd common reason (Disconnected) %,Apple iOS,01-06-2024,6.883
4,3rd common reason (Incomplete Install),Apple iOS,01-06-2024,37.000

In [54]:
# Step 10: Calculate 1st and 3rd quartiles
quartiles = melted_df.groupby(['Operating System Type', 'Metric'])['Value'].quantile([0.25, 0.75]).unstack()
quartiles.reset_index(inplace=True)
quartiles.columns.name = None  # Remove the index name
quartiles.columns = ['Operating System Type', 'Metric', '1st Quartile', '3rd Quartile']

# Step 11: Calculate IQR
quartiles['IQR'] = quartiles['3rd Quartile'] - quartiles['1st Quartile']

# Step 12: Calculate Upper and Lower bounds
# For all metrics except "Devices Page Visits"
quartiles.loc[quartiles['Metric'] != 'Devices Page Visits', 'Upper'] = quartiles['3rd Quartile'] + (0.75 * quartiles['IQR'])
quartiles.loc[quartiles['Metric'] != 'Devices Page Visits', 'Lower'] = quartiles['1st Quartile'] - (0.75 * quartiles['IQR'])

# Special case for "Devices Page Visits"
devices_page_visits = quartiles[quartiles['Metric'] == 'Devices Page Visits']
quartiles.loc[quartiles['Metric'] == 'Devices Page Visits', 'Upper'] = devices_page_visits['3rd Quartile'] + (1.25 * devices_page_visits['IQR'])
quartiles.loc[quartiles['Metric'] == 'Devices Page Visits', 'Lower'] = devices_page_visits['1st Quartile'] - (1.25 * devices_page_visits['IQR'])
quartiles

,Operating System Type,Metric,1st Quartile,3rd Quartile,IQR,Upper,Lower
0,Apple iOS,1st common reason (Unknown),111.25000,161.00000,49.75000,198.312500,73.937500
1,Apple iOS,1st common reason (Unknown) %,55.98300,63.88200,7.89900,69.806250,50.058750
2,Apple iOS,2nd common reason (Disconnected),8.00000,13.00000,5.00000,16.750000,4.250000
3,Apple iOS,2nd common reason (Disconnected) %,3.79900,6.28600,2.48700,8.151250,1.933750
4,Apple iOS,3rd common reason (Incomplete Install),20.00000,30.50000,10.50000,38.375000,12.125000
...,...,...,...,...,...,...,...
83,Google Android,Started P&P troubleshooting %,52.96300,55.94425,2.98125,58.180187,50.727063
84,Google Android,Started Proactive and Preventive (P&P),845.00000,1009.00000,164.00000,1132.000000,722.000000
85,Google Android,Started Proactive and Preventive (P&P) %,50.66650,54.65525,3.98875,57.646812,47.674937
86,Google Android,Started Troubleshooting (Solution Center),936.50000,1101.50000,165.00000,1225.250000,812.750000
87,Google Android,Started Troubleshooting (Solution Center) %,56.12075,59.01200,2.89125,61.180437,53.952313

In [55]:
# Merge quartiles with the pivoted DataFrame
df = pd.merge(combined_df1, quartiles, on=['Operating System Type', 'Metric'], how='left')
df.shape

(88, 97)

In [56]:
df.head()

,Operating System Type,Metric,01-06-2024,01-07-2024,01-08-2024,02-06-2024,02-07-2024,02-08-2024,03-06-2024,03-07-2024,...,30-05-2024,30-06-2024,30-07-2024,31-05-2024,31-07-2024,1st Quartile,3rd Quartile,IQR,Upper,Lower
0,Apple iOS,1st common reason (Unknown),146.000,161.000,112.000,158.000,152.000,115.000,167.000,131.000,...,172.000,149.000,115.000,181.000,130.000,111.250,161.000,49.750,198.31250,73.93750
1,Apple iOS,1st common reason (Unknown) %,59.109,53.846,53.589,54.483,58.015,55.556,51.863,50.385,...,59.107,66.518,59.278,70.428,59.361,55.983,63.882,7.899,69.80625,50.05875
2,Apple iOS,2nd common reason (Disconnected),17.000,7.000,8.000,13.000,10.000,10.000,8.000,11.000,...,12.000,13.000,10.000,14.000,14.000,8.000,13.000,5.000,16.75000,4.25000
3,Apple iOS,2nd common reason (Disconnected) %,6.883,2.341,3.828,4.483,3.817,4.831,2.484,4.231,...,4.124,5.804,5.155,5.447,6.393,3.799,6.286,2.487,8.15125,1.93375
4,Apple iOS,3rd common reason (Incomplete Install),37.000,29.000,29.000,23.000,39.000,23.000,28.000,29.000,...,22.000,19.000,26.000,25.000,21.000,20.000,30.500,10.500,38.37500,12.12500

In [57]:
# Identify date columns
date_columns = [col for col in df.columns if pd.to_datetime(col, format='%d-%m-%Y', errors='coerce') is not pd.NaT]
# Convert the identified date columns to datetime
date_columns_dt = pd.to_datetime(date_columns, format='%d-%m-%Y')
# Find the latest date column
latest_date_col = date_columns[date_columns_dt.argmax()]
# Create a new column with the latest date's values
df['Yesterday'] = df[latest_date_col]
df.head()

,Operating System Type,Metric,01-06-2024,01-07-2024,01-08-2024,02-06-2024,02-07-2024,02-08-2024,03-06-2024,03-07-2024,...,30-06-2024,30-07-2024,31-05-2024,31-07-2024,1st Quartile,3rd Quartile,IQR,Upper,Lower,Yesterday
0,Apple iOS,1st common reason (Unknown),146.000,161.000,112.000,158.000,152.000,115.000,167.000,131.000,...,149.000,115.000,181.000,130.000,111.250,161.000,49.750,198.31250,73.93750,54.000
1,Apple iOS,1st common reason (Unknown) %,59.109,53.846,53.589,54.483,58.015,55.556,51.863,50.385,...,66.518,59.278,70.428,59.361,55.983,63.882,7.899,69.80625,50.05875,79.412
2,Apple iOS,2nd common reason (Disconnected),17.000,7.000,8.000,13.000,10.000,10.000,8.000,11.000,...,13.000,10.000,14.000,14.000,8.000,13.000,5.000,16.75000,4.25000,9.000
3,Apple iOS,2nd common reason (Disconnected) %,6.883,2.341,3.828,4.483,3.817,4.831,2.484,4.231,...,5.804,5.155,5.447,6.393,3.799,6.286,2.487,8.15125,1.93375,13.235
4,Apple iOS,3rd common reason (Incomplete Install),37.000,29.000,29.000,23.000,39.000,23.000,28.000,29.000,...,19.000,26.000,25.000,21.000,20.000,30.500,10.500,38.37500,12.12500,3.000

In [58]:
# Find the latest date column
latest_date_index = date_columns_dt.argmax()
latest_date_col = date_columns[latest_date_index]

# Get columns prior to the latest date
prior_date_columns = date_columns[:latest_date_index]

# Get the last 7 of those prior date columns
last_7_prior_columns = prior_date_columns[-7:]

# Calculate the mean for each row across the last 7 prior date columns
df['Last 7 Days'] = df[last_7_prior_columns].mean(axis=1)
df.head()

,Operating System Type,Metric,01-06-2024,01-07-2024,01-08-2024,02-06-2024,02-07-2024,02-08-2024,03-06-2024,03-07-2024,...,30-07-2024,31-05-2024,31-07-2024,1st Quartile,3rd Quartile,IQR,Upper,Lower,Yesterday,Last 7 Days
0,Apple iOS,1st common reason (Unknown),146.000,161.000,112.000,158.000,152.000,115.000,167.000,131.000,...,115.000,181.000,130.000,111.250,161.000,49.750,198.31250,73.93750,54.000,113.000000
1,Apple iOS,1st common reason (Unknown) %,59.109,53.846,53.589,54.483,58.015,55.556,51.863,50.385,...,59.278,70.428,59.361,55.983,63.882,7.899,69.80625,50.05875,79.412,64.127571
2,Apple iOS,2nd common reason (Disconnected),17.000,7.000,8.000,13.000,10.000,10.000,8.000,11.000,...,10.000,14.000,14.000,8.000,13.000,5.000,16.75000,4.25000,9.000,9.428571
3,Apple iOS,2nd common reason (Disconnected) %,6.883,2.341,3.828,4.483,3.817,4.831,2.484,4.231,...,5.155,5.447,6.393,3.799,6.286,2.487,8.15125,1.93375,13.235,5.708714
4,Apple iOS,3rd common reason (Incomplete Install),37.000,29.000,29.000,23.000,39.000,23.000,28.000,29.000,...,26.000,25.000,21.000,20.000,30.500,10.500,38.37500,12.12500,3.000,21.000000

In [59]:
# Get the last 7 of those prior date columns
last_30_prior_columns = prior_date_columns[-30:]

# Calculate the mean for each row across the last 30 prior date columns
df['Last 30 Days'] = df[last_30_prior_columns].mean(axis=1)
df.head()

,Operating System Type,Metric,01-06-2024,01-07-2024,01-08-2024,02-06-2024,02-07-2024,02-08-2024,03-06-2024,03-07-2024,...,31-05-2024,31-07-2024,1st Quartile,3rd Quartile,IQR,Upper,Lower,Yesterday,Last 7 Days,Last 30 Days
0,Apple iOS,1st common reason (Unknown),146.000,161.000,112.000,158.000,152.000,115.000,167.000,131.000,...,181.000,130.000,111.250,161.000,49.750,198.31250,73.93750,54.000,113.000000,133.200000
1,Apple iOS,1st common reason (Unknown) %,59.109,53.846,53.589,54.483,58.015,55.556,51.863,50.385,...,70.428,59.361,55.983,63.882,7.899,69.80625,50.05875,79.412,64.127571,64.546100
2,Apple iOS,2nd common reason (Disconnected),17.000,7.000,8.000,13.000,10.000,10.000,8.000,11.000,...,14.000,14.000,8.000,13.000,5.000,16.75000,4.25000,9.000,9.428571,10.800000
3,Apple iOS,2nd common reason (Disconnected) %,6.883,2.341,3.828,4.483,3.817,4.831,2.484,4.231,...,5.447,6.393,3.799,6.286,2.487,8.15125,1.93375,13.235,5.708714,6.191100
4,Apple iOS,3rd common reason (Incomplete Install),37.000,29.000,29.000,23.000,39.000,23.000,28.000,29.000,...,25.000,21.000,20.000,30.500,10.500,38.37500,12.12500,3.000,21.000000,21.366667

In [60]:
# Sort the date columns
sorted_date_columns = sorted(date_columns, key=lambda x: pd.to_datetime(x, format='%d-%m-%Y'))

# Reorder the DataFrame with sorted date columns
sorted_columns = ['Operating System Type', 'Metric', ] + sorted_date_columns + ['1st Quartile', '3rd Quartile', 'IQR', 'Upper', 'Lower', 'Yesterday', 'Last 7 Days', 'Last 30 Days']
df1 = df[sorted_columns]

In [61]:
df1.head()

,Operating System Type,Metric,30-05-2024,31-05-2024,01-06-2024,02-06-2024,03-06-2024,04-06-2024,05-06-2024,06-06-2024,...,26-08-2024,27-08-2024,1st Quartile,3rd Quartile,IQR,Upper,Lower,Yesterday,Last 7 Days,Last 30 Days
0,Apple iOS,1st common reason (Unknown),172.000,181.000,146.000,158.000,167.000,184.000,146.000,154.000,...,52.000,54.000,111.250,161.000,49.750,198.31250,73.93750,54.000,113.000000,133.200000
1,Apple iOS,1st common reason (Unknown) %,59.107,70.428,59.109,54.483,51.863,56.790,55.939,69.369,...,77.612,79.412,55.983,63.882,7.899,69.80625,50.05875,79.412,64.127571,64.546100
2,Apple iOS,2nd common reason (Disconnected),12.000,14.000,17.000,13.000,8.000,11.000,15.000,8.000,...,5.000,9.000,8.000,13.000,5.000,16.75000,4.25000,9.000,9.428571,10.800000
3,Apple iOS,2nd common reason (Disconnected) %,4.124,5.447,6.883,4.483,2.484,3.395,5.747,3.604,...,7.463,13.235,3.799,6.286,2.487,8.15125,1.93375,13.235,5.708714,6.191100
4,Apple iOS,3rd common reason (Incomplete Install),22.000,25.000,37.000,23.000,28.000,36.000,40.000,22.000,...,6.000,3.000,20.000,30.500,10.500,38.37500,12.12500,3.000,21.000000,21.366667

In [62]:
df1['Metric'].unique()

array(['1st common reason (Unknown)', '1st common reason (Unknown) %',
       '2nd common reason (Disconnected)',
       '2nd common reason (Disconnected) %',
       '3rd common reason (Incomplete Install)',
       '3rd common reason (Incomplete Install) %',
       'Clicked Billing & Account Support',
       'Clicked Billing & Account Support %', 'Clicked Homelife Support',
       'Clicked Homelife Support %', 'Clicked Internet Support',
       'Clicked Internet Support %', 'Clicked TV Support',
       'Clicked TV Support %', 'Connect with Agent',
       'Connect with Agent %', 'Devices Page Visits',
       'Did a Device Reboot', 'Did a Device Reboot %',
       'Interacted with Chat', 'Interacted with Chat %',
       'Interacted with Chat_1', 'Interacted with Chat_1 %',
       'Reset Complete', 'Reset Complete %', 'Saw a Result',
       'Saw a Result %', 'Schedule Tech', 'Schedule Tech %',
       'Started P&P troubleshooting', 'Started P&P troubleshooting %',
       'Started Proactive and Preventive (P&P)',
       'Started Proactive and Preventive (P&P) %',
       'Started Troubleshooting (Solution Center)',
       'Started Troubleshooting (Solution Center) %'], dtype=object)

In [63]:
# Specify the metric values you want to filter
specific_metrics = ['1st common reason (Unknown) %', '2nd common reason (Disconnected) %','3rd common reason (Incomplete Install) %',
       'Clicked Billing & Account Support %','Clicked Homelife Support %','Clicked Internet Support %',
       'Clicked TV Support %','Connect with Agent %', 'Devices Page Visits',
      'Did a Device Reboot %', 'Interacted with Chat %', 'Interacted with Chat_1 %', 
      'Reset Complete %','Saw a Result %','Schedule Tech %',
        'Started P&P troubleshooting %', 'Started Proactive and Preventive (P&P) %','Started Troubleshooting (Solution Center) %']

# Filter the DataFrame
filtered_df = df1[df1['Metric'].isin(specific_metrics)]
filtered_df.head()

,Operating System Type,Metric,30-05-2024,31-05-2024,01-06-2024,02-06-2024,03-06-2024,04-06-2024,05-06-2024,06-06-2024,...,26-08-2024,27-08-2024,1st Quartile,3rd Quartile,IQR,Upper,Lower,Yesterday,Last 7 Days,Last 30 Days
1,Apple iOS,1st common reason (Unknown) %,59.107,70.428,59.109,54.483,51.863,56.790,55.939,69.369,...,77.612,79.412,55.98300,63.88200,7.89900,69.806250,50.058750,79.412,64.127571,64.546100
3,Apple iOS,2nd common reason (Disconnected) %,4.124,5.447,6.883,4.483,2.484,3.395,5.747,3.604,...,7.463,13.235,3.79900,6.28600,2.48700,8.151250,1.933750,13.235,5.708714,6.191100
5,Apple iOS,3rd common reason (Incomplete Install) %,7.560,9.728,14.980,7.931,8.696,11.111,15.326,9.910,...,8.955,4.412,8.88150,12.50000,3.61850,15.213875,6.167625,4.412,10.720571,9.825900
7,Apple iOS,Clicked Billing & Account Support %,17.685,20.337,19.643,16.608,21.354,18.812,19.975,18.949,...,20.468,20.041,16.83075,19.23575,2.40500,21.039500,15.027000,20.041,17.538286,17.512967
9,Apple iOS,Clicked Homelife Support %,0.297,0.296,0.227,0.494,0.268,0.176,0.434,0.384,...,0.409,0.441,0.20625,0.33150,0.12525,0.425438,0.112312,0.441,0.264286,0.265533

In [65]:
filtered_df['Metric'].value_counts()

Metric
1st common reason (Unknown) %                  3
2nd common reason (Disconnected) %             3
Started Proactive and Preventive (P&P) %       3
Started P&P troubleshooting %                  3
Schedule Tech %                                3
Saw a Result %                                 3
Reset Complete %                               3
Interacted with Chat_1 %                       3
Interacted with Chat %                         3
Did a Device Reboot %                          3
Devices Page Visits                            3
Connect with Agent %                           3
Clicked TV Support %                           3
Clicked Internet Support %                     3
Clicked Homelife Support %                     3
Clicked Billing & Account Support %            3
3rd common reason (Incomplete Install) %       3
Started Troubleshooting (Solution Center) %    3
Name: count, dtype: int64

In [66]:
filtered_df = filtered_df.drop(columns=['1st Quartile', '3rd Quartile', 'IQR'])

In [67]:
filtered_df.shape

(54, 97)

In [68]:
filtered_df['% Change Last 7 Days'] =  (filtered_df['Yesterday']- filtered_df['Last 7 Days'])/filtered_df['Last 7 Days']
filtered_df.head()

,Operating System Type,Metric,30-05-2024,31-05-2024,01-06-2024,02-06-2024,03-06-2024,04-06-2024,05-06-2024,06-06-2024,...,24-08-2024,25-08-2024,26-08-2024,27-08-2024,Upper,Lower,Yesterday,Last 7 Days,Last 30 Days,% Change Last 7 Days
1,Apple iOS,1st common reason (Unknown) %,59.107,70.428,59.109,54.483,51.863,56.790,55.939,69.369,...,72.308,81.081,77.612,79.412,69.806250,50.058750,79.412,64.127571,64.546100,0.238344
3,Apple iOS,2nd common reason (Disconnected) %,4.124,5.447,6.883,4.483,2.484,3.395,5.747,3.604,...,10.769,9.459,7.463,13.235,8.151250,1.933750,13.235,5.708714,6.191100,1.318385
5,Apple iOS,3rd common reason (Incomplete Install) %,7.560,9.728,14.980,7.931,8.696,11.111,15.326,9.910,...,10.769,6.757,8.955,4.412,15.213875,6.167625,4.412,10.720571,9.825900,-0.588455
7,Apple iOS,Clicked Billing & Account Support %,17.685,20.337,19.643,16.608,21.354,18.812,19.975,18.949,...,17.040,16.119,20.468,20.041,21.039500,15.027000,20.041,17.538286,17.512967,0.142700
9,Apple iOS,Clicked Homelife Support %,0.297,0.296,0.227,0.494,0.268,0.176,0.434,0.384,...,0.328,0.201,0.409,0.441,0.425438,0.112312,0.441,0.264286,0.265533,0.668649

In [69]:
filtered_df['% Change Last 30 Days'] =  (filtered_df['Yesterday']- filtered_df['Last 30 Days'])/filtered_df['Last 30 Days']
filtered_df.head()

,Operating System Type,Metric,30-05-2024,31-05-2024,01-06-2024,02-06-2024,03-06-2024,04-06-2024,05-06-2024,06-06-2024,...,25-08-2024,26-08-2024,27-08-2024,Upper,Lower,Yesterday,Last 7 Days,Last 30 Days,% Change Last 7 Days,% Change Last 30 Days
1,Apple iOS,1st common reason (Unknown) %,59.107,70.428,59.109,54.483,51.863,56.790,55.939,69.369,...,81.081,77.612,79.412,69.806250,50.058750,79.412,64.127571,64.546100,0.238344,0.230314
3,Apple iOS,2nd common reason (Disconnected) %,4.124,5.447,6.883,4.483,2.484,3.395,5.747,3.604,...,9.459,7.463,13.235,8.151250,1.933750,13.235,5.708714,6.191100,1.318385,1.137746
5,Apple iOS,3rd common reason (Incomplete Install) %,7.560,9.728,14.980,7.931,8.696,11.111,15.326,9.910,...,6.757,8.955,4.412,15.213875,6.167625,4.412,10.720571,9.825900,-0.588455,-0.550983
7,Apple iOS,Clicked Billing & Account Support %,17.685,20.337,19.643,16.608,21.354,18.812,19.975,18.949,...,16.119,20.468,20.041,21.039500,15.027000,20.041,17.538286,17.512967,0.142700,0.144352
9,Apple iOS,Clicked Homelife Support %,0.297,0.296,0.227,0.494,0.268,0.176,0.434,0.384,...,0.201,0.409,0.441,0.425438,0.112312,0.441,0.264286,0.265533,0.668649,0.660808

In [70]:
filtered_df['Metric + OS'] = filtered_df['Metric']+ ' ' + filtered_df['Operating System Type']
filtered_df.head()

,Operating System Type,Metric,30-05-2024,31-05-2024,01-06-2024,02-06-2024,03-06-2024,04-06-2024,05-06-2024,06-06-2024,...,26-08-2024,27-08-2024,Upper,Lower,Yesterday,Last 7 Days,Last 30 Days,% Change Last 7 Days,% Change Last 30 Days,Metric + OS
1,Apple iOS,1st common reason (Unknown) %,59.107,70.428,59.109,54.483,51.863,56.790,55.939,69.369,...,77.612,79.412,69.806250,50.058750,79.412,64.127571,64.546100,0.238344,0.230314,1st common reason (Unknown) % Apple iOS
3,Apple iOS,2nd common reason (Disconnected) %,4.124,5.447,6.883,4.483,2.484,3.395,5.747,3.604,...,7.463,13.235,8.151250,1.933750,13.235,5.708714,6.191100,1.318385,1.137746,2nd common reason (Disconnected) % Apple iOS
5,Apple iOS,3rd common reason (Incomplete Install) %,7.560,9.728,14.980,7.931,8.696,11.111,15.326,9.910,...,8.955,4.412,15.213875,6.167625,4.412,10.720571,9.825900,-0.588455,-0.550983,3rd common reason (Incomplete Install) % Apple...
7,Apple iOS,Clicked Billing & Account Support %,17.685,20.337,19.643,16.608,21.354,18.812,19.975,18.949,...,20.468,20.041,21.039500,15.027000,20.041,17.538286,17.512967,0.142700,0.144352,Clicked Billing & Account Support % Apple iOS
9,Apple iOS,Clicked Homelife Support %,0.297,0.296,0.227,0.494,0.268,0.176,0.434,0.384,...,0.409,0.441,0.425438,0.112312,0.441,0.264286,0.265533,0.668649,0.660808,Clicked Homelife Support % Apple iOS

In [71]:
filtered_df.to_csv('COX_data_V4.csv', index = False)