In [10]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv(r"D:\shalini\HS_DataClean_Nov.csv")

In [17]:
df.head()

,Metrics,Operating System Type,29-08-2024,30-08-2024,31-08-2024,01-09-2024,02-09-2024,03-09-2024,04-09-2024,05-09-2024,06-09-2024,07-09-2024,08-09-2024,09-09-2024,10-09-2024,11-09-2024,12-09-2024,13-09-2024,14-09-2024,15-09-2024,16-09-2024,17-09-2024,18-09-2024,19-09-2024,20-09-2024,21-09-2024,22-09-2024,23-09-2024,24-09-2024,25-09-2024,26-09-2024,27-09-2024,28-09-2024,29-09-2024,30-09-2024,01-10-2024,02-10-2024,03-10-2024,04-10-2024,05-10-2024,06-10-2024,07-10-2024,08-10-2024,09-10-2024,10-10-2024,11-10-2024,12-10-2024,13-10-2024,14-10-2024,15-10-2024,16-10-2024,17-10-2024,18-10-2024,19-10-2024,20-10-2024,21-10-2024,22-10-2024,23-10-2024,24-10-2024,25-10-2024,26-10-2024,27-10-2024,28-10-2024,29-10-2024,30-10-2024,31-10-2024,01-11-2024,02-11-2024,03-11-2024,04-11-2024,05-11-2024,06-11-2024,07-11-2024,08-11-2024,09-11-2024,10-11-2024,11-11-2024,12-11-2024,13-11-2024,14-11-2024,15-11-2024,16-11-2024,17-11-2024,18-11-2024,19-11-2024,20-11-2024,21-11-2024,22-11-2024,23-11-2024,24-11-2024,25-11-2024,26-11-2024
0,DR_Visits,Apple iOS,128972.0,134545.0,108365.0,103404.0,105826.0,127210.0,137281.0,146572.0,141889.0,108118.0,102838.0,118429.0,122323.0,129946.0,152282.0,141748.0,107332.0,102817.0,117617.0,118093.0,119881.0,126088.0,129406.0,102987.0,98899.0,114372.0,123407.0,124933.0,125706.0,142355.0,114368.0,101759.0,132135.0,141110.0,133880.0,132754.0,131119.0,105654.0,96486.0,112188.0,117077.0,123958.0,127023.0,127876.0,99058.0,98029.0,115678.0,125414.0,126731.0,123948.0,133195.0,101670.0,97033.0,113800.0,119353.0,117556.0,119793.0,125275.0,95221.0,87926.0,107856.0,109933.0,116873.0,118308.0,141845.0,110226.0,116364.0,120916.0,117477.0,115346.0,125630.0,133289.0,103236.0,91648.0,109161.0,117546.0,119930.0,137142.0,163023.0,105686.0,96647.0,117342.0,116002.0,123237.0,122039.0,128582.0,105323.0,96961.0,116462.0,114579.0
1,DR_Visits,Google Android,40690.0,43480.0,34724.0,32386.0,33232.0,40641.0,44631.0,46753.0,45045.0,34576.0,32174.0,36852.0,38306.0,40869.0,46111.0,44145.0,34076.0,34094.0,36106.0,36928.0,37546.0,39575.0,40341.0,32036.0,30697.0,34641.0,37721.0,39345.0,39376.0,44765.0,35588.0,31570.0,40018.0,44625.0,42834.0,44437.0,42525.0,34162.0,30707.0,35096.0,37028.0,39503.0,40731.0,40529.0,31907.0,30919.0,35064.0,37965.0,39414.0,39006.0,42228.0,32531.0,30318.0,37042.0,37939.0,36856.0,37462.0,39687.0,30798.0,28134.0,33592.0,34621.0,36689.0,37624.0,47646.0,35988.0,37451.0,37953.0,36950.0,36824.0,40050.0,42035.0,33612.0,28967.0,34123.0,36825.0,38062.0,43221.0,50987.0,34197.0,30506.0,35761.0,35996.0,38003.0,37647.0,40800.0,34032.0,30643.0,35820.0,35696.0
2,Unique Visitors,Apple iOS,110767.0,115562.0,92714.0,89445.0,92056.0,108297.0,113518.0,122365.0,119807.0,92064.0,88658.0,101371.0,103432.0,110280.0,121506.0,120019.0,91737.0,89398.0,100244.0,98049.0,102432.0,106623.0,110738.0,88688.0,86621.0,97990.0,104514.0,107176.0,105431.0,117353.0,95875.0,88261.0,113075.0,120655.0,111213.0,113426.0,112570.0,92016.0,84920.0,96225.0,98975.0,105650.0,108164.0,110396.0,86107.0,82902.0,99013.0,105637.0,107781.0,106290.0,114624.0,87977.0,85229.0,97615.0,101478.0,100225.0,102858.0,107532.0,83577.0,77134.0,92853.0,94444.0,100252.0,102322.0,120968.0,95041.0,97950.0,101531.0,100547.0,98837.0,106911.0,113887.0,88280.0,83467.0,93323.0,98541.0,102679.0,116443.0,138681.0,90785.0,84391.0,99974.0,98937.0,107501.0,106064.0,112656.0,90600.0,84110.0,101365.0,99610.0
3,Unique Visitors,Google Android,36310.0,38629.0,31252.0,29564.0,30275.0,36012.0,38087.0,40339.0,39461.0,30919.0,29144.0,33010.0,33860.0,36077.0,39007.0,38742.0,30617.0,30711.0,32370.0,31765.0,33376.0,34868.0,35882.0,28978.0,28100.0,31031.0,33120.0,34657.0,34263.0,38147.0,31187.0,28628.0,35613.0,39324.0,36882.0,39116.0,37980.0,30943.0,28409.0,31461.0,32535.0,34824.0,36094.0,36217.0,28907.0,27327.0,31341.0,33238.0,34677.0,34888.0,37547.0,29379.0,27992.0,32990.0,33275.0,32765.0,33602.0,35315.0,28169.0,25847.0,30207.0,30868.0,32681.0,33728.0,41407.0,31990.0,32478.0,33038.0,32961.0,32891.0,35533.0,37260.0,29912.0,27769.0,30465.0,32099.0,33823.0,37927.0,44407.0,30508.0,27863.0,31745.0,31859.0,34808.0,34364.0,36815.0,30375.0,27868.0,32319.0,32219.0
4,Page Views,Apple iOS,1660279.0,1747960.0,1425948.0,1327881.0,1379682.0,1652733.0,1793373.0,1966096.0,1882165.0,1435487.0,1315738.0,1506212.0,1543871.0,1627883.0,1861624.0,1780144.0,1400981.0,1332593.0,1511755.0,1476681.0,1550306.0,1553558.0,1663606.0,1352836.0,1266771.0,1474748.0,1590824.0,1597074.0,1593828.0,1781297.0,1463865.0,1280226.0,1670384.0,1803669.0,1688099.0,1696375.0,1686165.0,1376783.0,1228893.0,1430433.0,1469030.0,1565479.0,1599303.0,1636916.0,1280164.0,1129048.0,1481583.0,1569969.0,1616783.0,1575826.0,1697687.0,1338805.0,1229853.0,1466023.0,1530198.0,1491370.0,1525753.0,1589659.0,1241622.0,1111797.0,1378131.0,1406196.0,1484899.0,1488956.0,1803669.0,1448117.0,1466069.0,1553722.0,1481703.0,1460555.0,1593319.0,1705427.0,1371463.0,1183794.0,1414167.0,1489652.0,1542392.0,1769631.0,2049808.0,1430429.0,1262735.0,1506039.0,1518198.0,1630633.0,1622723.0,1692333.0,1436513.0,1272222.0,1524040.0,1532116.0

In [ ]:
derived_metrics = df[df['metrics'].isin(['DR_Visits', 'Average Time Spent on Page', 'Page Views','DR_Direct Ecomm order Traffic sent from App to cox.com','DR_Direct Ecomm Traffic sent from App to cox.com', ])]

In [11]:
def calculate_metrics(df, new_row_display_name, numerator_display_name, denominator_display_name, operation):
    """
    Calculate and append a new row based on the given display names for the numerator and denominator, 
    and an operation ('multiply' or 'divide') to be applied.

    Args:
        df (pd.DataFrame): The input DataFrame containing the original data.
        new_row_display_name (str): The name of the new row (metric) to generate (e.g., 'Total Time spent').
        numerator_display_name (str): The display name used as the numerator for the formula.
        denominator_display_name (str): The display name used as the denominator for the formula.
        operation (str): The operation to perform - 'multiply' or 'divide'.

    Returns:
        pd.DataFrame: The updated DataFrame with the calculated metric appended.
    """
    os_types = df['operating_system_type'].unique()  # Get unique OS types (ios, android)
    new_rows = []

    # Loop over each operating system type
    for os in os_types:
        os_data = df[df['operating_system_type'] == os]  # Filter data for the specific OS
        
        # Extract the relevant values based on display_names
        numerator_values = os_data[os_data['display_names'] == numerator_display_name].iloc[:, 2:].values
        denominator_values = os_data[os_data['display_names'] == denominator_display_name].iloc[:, 2:].values
        
        # Ensure the operation is either 'multiply' or 'divide'
        if operation == 'multiply':
            result = numerator_values * denominator_values
        elif operation == 'divide':
            result = numerator_values / denominator_values
        else:
            raise ValueError("Operation must be 'multiply' or 'divide'")

        # Initialize a dictionary to hold the values for the new row
        new_row_values = {df.columns[i]: result[0][i-2] for i in range(2, len(df.columns))}

        # Append the calculated values as a new row in the correct format
        new_rows.append({
            'display_names': new_row_display_name,
            'operating_system_type': os,
            **new_row_values
        })
    
    # Create a DataFrame for the new rows
    new_df = pd.DataFrame(new_rows)

    # Concatenate the new rows with the original DataFrame
    df = pd.concat([df, new_df], ignore_index=True)

    return df

In [12]:
# Sample DataFrame with dummy data
data = {
    'display_names': [
        'Visits', 'Average Time Spent (mins)', 'Page Views', 'Orders generated',
        'Visits sent from app to cox.com', 'Total Orders from web ecomm', 'Total Visits from web ecomm'
    ] * 2,
    'operating_system_type': ['ios'] * 7 + ['android'] * 7,
    '11-02-2024': np.random.randint(50, 150, 14),
    '12-02-2024': np.random.randint(50, 150, 14),
    '13-02-2024': np.random.randint(50, 150, 14),
    '14-02-2024': np.random.randint(50, 150, 14),
    '15-02-2024': np.random.randint(50, 150, 14)
}

In [13]:
df = pd.DataFrame(data)
df.head()

,display_names,operating_system_type,11-02-2024,12-02-2024,13-02-2024,14-02-2024,15-02-2024
0,Visits,ios,55,78,113,115,92
1,Average Time Spent (mins),ios,59,78,127,72,57
2,Page Views,ios,122,127,56,60,124
3,Orders generated,ios,100,98,57,91,107
4,Visits sent from app to cox.com,ios,88,66,114,118,109

In [14]:
# Prepare the arguments in a dictionary
metrics_args = [
    {
        'new_row_display_name': 'Total Time spent',
        'numerator_display_name': 'Visits',
        'denominator_display_name': 'Average Time Spent (mins)',
        'operation': 'multiply'
    },
    {
        'new_row_display_name': 'Page Views per Visit',
        'numerator_display_name': 'Page Views',
        'denominator_display_name': 'Visits',
        'operation': 'divide'
    },
    {
        'new_row_display_name': 'Order Conversion',
        'numerator_display_name': 'Orders generated',
        'denominator_display_name': 'Visits sent from app to cox.com',
        'operation': 'divide'
    },
    {
        'new_row_display_name': 'Share of orders - app to total web ecomm',
        'numerator_display_name': 'Orders generated',
        'denominator_display_name': 'Total Orders from web ecomm',
        'operation': 'divide'
    },
    {
        'new_row_display_name': 'Share of visits - app to total web ecomm',
        'numerator_display_name': 'Visits sent from app to cox.com',
        'denominator_display_name': 'Total Visits from web ecomm',
        'operation': 'divide'
    }
]

In [15]:
for args in metrics_args:
    df = calculate_metrics(df, **args)

# Print the updated DataFrame with calculated rows
print("\nUpdated DataFrame with calculated rows:")
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', 100)
print(df)

Updated DataFrame with calculated rows:
                               display_names operating_system_type  \
0                                     Visits                   ios
1                  Average Time Spent (mins)                   ios
2                                 Page Views                   ios
3                           Orders generated                   ios
4            Visits sent from app to cox.com                   ios
5                Total Orders from web ecomm                   ios
6                Total Visits from web ecomm                   ios
7                                     Visits               android
8                  Average Time Spent (mins)               android
9                                 Page Views               android
10                          Orders generated               android
11           Visits sent from app to cox.com               android
12               Total Orders from web ecomm               android
13               Total Visits from web ecomm               android
14                          Total Time spent                   ios
15                          Total Time spent               android
16                      Page Views per Visit                   ios
17                      Page Views per Visit               android
18                          Order Conversion                   ios
19                          Order Conversion               android
20  Share of orders - app to total web ecomm                   ios
21  Share of orders - app to total web ecomm               android
22  Share of visits - app to total web ecomm                   ios
23  Share of visits - app to total web ecomm               android

     11-02-2024   12-02-2024    13-02-2024   14-02-2024   15-02-2024
0     55.000000    78.000000    113.000000   115.000000    92.000000
1     59.000000    78.000000    127.000000    72.000000    57.000000
2    122.000000   127.000000     56.000000    60.000000   124.000000
3    100.000000    98.000000     57.000000    91.000000   107.000000
4     88.000000    66.000000    114.000000   118.000000   109.000000
5    132.000000    68.000000    126.000000   144.000000    74.000000
6    108.000000    68.000000    132.000000    76.000000    95.000000
7    120.000000    59.000000     77.000000   148.000000   112.000000
8     82.000000    76.000000    141.000000    67.000000    69.000000
9    141.000000   120.000000     91.000000    65.000000   145.000000
10    77.000000    69.000000     60.000000   108.000000    97.000000
11    51.000000    83.000000    110.000000    64.000000    60.000000
12   131.000000   126.000000     60.000000   101.000000   118.000000
13   117.000000   135.000000     77.000000    66.000000   149.000000
14  3245.000000  6084.000000  14351.000000  8280.000000  5244.000000
15  9840.000000  4484.000000  10857.000000  9916.000000  7728.000000
16     2.218182     1.628205      0.495575     0.521739     1.347826
17     1.175000     2.033898      1.181818     0.439189     1.294643
18     1.136364     1.484848      0.500000     0.771186     0.981651
19     1.509804     0.831325      0.545455     1.687500     1.616667
20     0.757576     1.441176      0.452381     0.631944     1.445946
21     0.587786     0.547619      1.000000     1.069307     0.822034
22     0.814815     0.970588      0.863636     1.552632     1.147368
23     0.435897     0.614815      1.428571     0.969697     0.402685